export const retentionTimeOptions = [
  "Don't autodelete",
  "After 5 minutes",
  "After 10 minutes",
  "After 15 minutes",
  "After 30 minutes",
  "After 1 hour",
  "After 3 hours",
  "After 6 hours",
  "After 12 hours",
  "After 1 day",
  "After 2 day",
  "After 3 day",
  "After 4 day",
  "After 5 day",
  "After 6 day",
  "After 1 week",
  "After 2 week",
  "After 3 week",
  "After 1 month",
  "After 2 month",
  "After 3 month",
  "After 4 month",
  "After 5 month",
  "After 6 month",
] as string[];
